export const SET_CURRENT_USER_SESSION = "SET_CURRENT_USER_SESSION";
export const CLEAR_CURRENT_USER_SESSION = "CLEAR_CURRENT_USER_SESSION";
export const GET_ERRORS = "GET_ERRORS";
export const CLEAR_ERRORS = "CLEAR_ERRORS";
export const UPLOAD_IMAGE = "UPLOAD_IMAGE";
export const GET_FACE_DETECTION_RESPONSE = "GET_FACE_DETECTION_RESPONSE";
